Algoritmo "sala_de_aula"

Var
// Seção de Declarações das variáveis 

comprimento, largura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("SEJA BEM VINDO AO SOFTWARE DE CÁLCULO POR MTRS2 DA M&M ENGENHARIA!")
escreva("Insira o comprimento em METROS: ")
leia(comprimento)
escreva("Insira a largura em METROS: ")
leia(largura)

area<- comprimento * largura

escreva("Sua ÁREA total é de: ", area, " mtrs")

Fimalgoritmo